FROM python:3.9-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . .
EXPOSE 80
ENTRYPOINT ["gunicorn", "app:app", "-b", "0.0.0.0:80"]