version: '3'

networks:
  rede-votos:

services:
  redis:
    image: redis:alpine
    networks:
      - rede-votos

  db:
    image: postgres:9.4
    networks:
      - rede-votos
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  voting-app:
    build: ./vote
    ports:
      - 5000:80
    networks:
      - rede-votos
    depends_on:
      - redis
      - db

  worker:
    build: ./worker
    networks:
      - rede-votos
    depends_on:
      - redis
      - db

  result-app: 
    build: ./result
    ports:
      - 5001:80
    networks:
      - rede-votos
    depends_on:
      - redis
      - db